language: ruby
rvm:
- 2.5.1
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAII2S3GRPXDR4R7NQ
  secret_access_key:
    secure: qEFzHunJ80oM3vLSgjNNq1NArmDp+zPvWagifh1Cb057RbieydjWZ1pNQFV7cDWq8l0Qrg72D1xujfsxjiSKdQHOrtzDGefjC0Dz0IwofXGXXHBRHdpvhF/oycqO2bBCzqeLo/SfR0tH001e6EEs2AkF4Utq81bV/OKrCHgIf3Vg1yLpcU09pi7O2QZphJHxLeEIefO+d22egA2ELM36YA+XeddvTtqRCW8k9V3UCg5c85ILtYg+P9jWMRUnarTTmpCFhRuN/qkmUoP/cUV/KcAdYcVLPp8673Q4RAejQsK5YnhJ7l7G6eZKdLZMMaMRmbckZ7wMySqzgg9m4bxo84l/r6mjckxMU35GwUyjpSfwzuH2oT6AEk1Ta5gc5zPZmBFA51Ivs/7dTpvMiLCqsaF5mGXIEoZwiH1BQ7oinsqarUuhxQtSfZRKl15gAygRsFZbrtUcNd7CAD1i+ZJ95uhVnhv08XOs+jLXNPugn2Ria6oNUZshB/a6IlcLN5JFQmoDzFjjRtSlHULASsPPBZQi4UqjPP5g4CuwsvYG6sX+mhbygYvrX+nGvsaTvFKnc6jPgqUGiiyw+QoeFMDdd/tNQxD38vh+6d4/1ATpCDdphcWmTSoyP6bohJXmPZO6Kp4JcHQob4fDKqboxJDpx1FRIJk+aWmnnxBIVlhmbNs=
  bucket: johnsey.me
  local-dir: _site
  acl: public_read
  on:
    repo: mjohnsey/johnsey.me
  skip_cleanup: true
