theme="hugo-theme-nix"
baseURL = "https://johnsey.me"
languageCode = "en-us"
title = "Michael Johnsey"
MetaDataFormat = "toml"
copyright = "Copyright Michael Johnsey ©2017"

[params]
  GithubID = "mjohnsey"
  TwitterID = "mcjohnsey"
  LinkedInID = "mjohnsey"
  # GoogleplusID = "+MichaelJohnsey901"
  FacebookID = "mcjohnsey"
  Name = "Michael Johnsey"
  HeaderUsername = "michael"
  HeaderHostname = "johnsey.me"
  Email = "michael@johnsey.me"
  About = "Hello, my name is Michael Johnsey. I'm currently a Software Engineer at Mosaik in Memphis, TN."
  ProfilePicture = "https://s.gravatar.com/avatar/cdc4466f7165f436529ca7c3316a304b?s=200"
  GoogleAnalytics = "UA-98280797-1"

[attributions]
  theme="https://github.com/LordMathis/hugo-theme-nix"
  favicon="https://paulferrett.com/fontawesome-favicon/"
