name: Generate Site
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.5.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run build
        run: scripts/cibuild
      - name: Commit changes to inventory.json
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Apply automatic changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
